### ISSUE TITLE
MG_SKYBLOCKLE Return Response

### ISSUE THREAD

**Issue by Duechayapol** [Noxcrew/mcchampionship-api#1]
Hello!

From the request I made for Hall of Fame, it seems like the Most Wins value for the player CaptainSparklez seems to be incorrect, as from the event's history, it seems that he has won only two rounds of Skyblockle, in MCC 3 and MCC 8, which is also tied with CaptainPuffy. (in MCC 7 and MCC 8)

![image](https://user-images.githubusercontent.com/32790772/175101727-b2718607-637a-4c2f-99ee-7738f501a692.png)

Let me know, if there is any questions. Thank you so much!
Due

**Comment by Aeltumn** [comment]
I've looked further into this and it seems there was an issue with how KaptainSparklez's data was transferred to the CaptainSparklez  account which lead among other issues to it counting MCC7 as a win for him. It'll be fixed on the API after MCC23.
