### ISSUE TITLE
[Request] Include event information

### ISSUE THREAD

**Issue by TheMysterys** [Noxcrew/mcchampionship-api#11]
It would be nice if we could have included in Rundown (or as part of the `/event` route) a way to get the event's date.

While I know there are other sources for this information like the event wiki. It would be nice to not have to manually enter this information into my collection.

This could be done like so:

`/rundown/{event}`
```json
{
	"code": 200,
	"event": 35,
	"date": "2023-12-09T20:00:00.000Z",
	"data": {
		EVENT DATA HERE
	}
}
```

or just allow us to call past events in the `/event` route with `/event/{event}`

Of course it's fine if this isn't added. It's more of a QoL thing that isn't really too necessaries just more of a nice to have.

**Comment by MagicA550** [comment]
Can you elaborate on exactly what data you would like to receive from the endpoint?

**Comment by TheMysterys** [comment]
Mostly I am just wanting the date the event happened on. Since if you're wanting to tie the date to an event there is no way to fetch it. 

Like say I want to find out what date MCC 14 happened on and the stats for the event, and display it all. I would have to call the API for the stats, and then manually find the date and insert it.

**Comment by MagicA550** [comment]
Hi there! Apologies for the time it's taken to get around to this issue. Unfortunately, this is going to have to be marked as something for later, but it is on my list as something to look into. I'll hopefully have some good news sometime in the future.
