### ISSUE TITLE
Requests blocked by Cloudflare on Hetzner

### ISSUE THREAD

**Issue by Bjornar97** [Noxcrew/mcchampionship-api#14]
Hi. I tried using this API on a server hosted on Hetzner. 
When sending a request I get a response saying Cloudflare blocked the request. 
Im planning on sending around 2 requests per day.

Is it possible for you to allow my IP address or something?

**Comment by Bjornar97** [comment]
Ray ID: 8eb3d4273bf09b4b

**Comment by clrxbl** [comment]
Please try again now.

**Comment by Bjornar97** [comment]
That worked! Fantastic! Thank you for the incredibly fast response :)
