### ISSUE TITLE
Bad CORS configuration

### ISSUE THREAD

**Issue by lolouthefox** [Noxcrew/mcchampionship-api#8]
While accessing any endpoints using javascript (via Axios at least) you get:

```
Access to XMLHttpRequest at 'https://api.mcchampionship.com/v1/participants' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
``` 

 There is no 'Access-Control-Allow-Origin' header on any of the API end points.

**Comment by MagicA550** [comment]
Should be fixed now, sorry about the issues!
