### ISSUE TITLE
Inaccurate data for some players in MCC 14

### ISSUE THREAD

**Issue by duechayapol-legacy** [Noxcrew/mcchampionship-api#9]
Hello,
From the MCC API, it seems that two of the players have their event coins incorrectly put in, when comparing the event coins from the players' VODs to the one that is on MCC.Live and MCC API. The two being:

- TheOrionSound = supposed to be 1871, but displayed as 1887
- Grian = supposed to be 1827, but displayed as 1811

The VODs in question are here: (from YouTube)
- TheOrionSound = [https://www.youtube.com/watch?v=23M0lW-d8ag](https://www.youtube.com/watch?v=23M0lW-d8ag)
- Grian = [https://www.youtube.com/watch?v=QedVsXGQxzg](https://www.youtube.com/watch?v=QedVsXGQxzg)

As far as I am aware, the scores were incorrect after the final individual coin amount from Game 8 (Parkour Tag) was added after Game 7 (Battle Box).

**Comment by MagicA550** [comment]
Hi there,

Many thanks for spotting this, it should be resolved now. Please let me know if there are any other inaccuracies.
